version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: stickerpack-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - ${DB_PORT}:${DB_PORT}
  api:
    build:
      context: ./apps/api
    container_name: stickerpack-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - BOT_NAME=${BOT_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

volumes:
  postgres-data: