version: "3.8"

services:
  api:
    build:
      context: ./apps/api
    container_name: stickerpack-api
    ports:
      - "8080:8080"
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - BOT_NAME=${BOT_NAME}
